#!/bin/bash

pacman -S --needed \
    hyprland \
    uwsm \
    xdg-desktop-portal \
    xdg-desktop-portal-hyprland \
    polkit \
    hyprpolkitagent \
    qt5-wayland \
    qt6-wayland \
    qt6-multimedia-ffmpeg \
    pipewire \
    pipewire-alsa \
    pipewire-pulse \
    pipewire-jack \
    wireplumber \
    nwg-look \
    hyprpaper \
    udiskie \
    waybar \
    ly \
    kitty \
    wofi \
    dolphin \
    dunst \
    adwaita-fonts \
    adwaita-icon-theme \
    adwaita-cursors \
    libva \
    libvdpau \
    mesa \
    fuse3 \
    fuse-common \
    x264 \
    x265 \
    bluez \
    bluez-utils \
    xorg-wayland

CONFIG_FILE="$HOME/.config/hypr/hyprland.conf"

# remove autogenerated lines in hyprland.conf
sed -i '0,/autogenerated = 1/s//\#autogenerated = 1/' "$CONFIG_FILE"

# hyprqt6engine
# https://wiki.hypr.land/Hypr-Ecosystem/hyprqt6engine/
# set "QT_QPA_PLATFORMTHEME=hyprqt6engine". You can set this as env= in Hyprland,

# hyprpolkitagent
# https://wiki.hypr.land/Hypr-Ecosystem/hyprpolkitagent/
# Add "exec-once = systemctl --user start hyprpolkitagent" to your Hyprland config

# udiskie
# https://wiki.hypr.land/Useful-Utilities/Other/#automatically-mounting-using-udiskie
#  Add "exec-once = udiskie" to hyprland.conf 

# waybar
# https://wiki.hypr.land/Useful-Utilities/Status-Bars/#waybar
# Add "exec-once = waybar" to your Hyprland config

cat <<'EOF' >> "$CONFIG_FILE"

##############
### CUSTOM ###
##############

env=QT_QPA_PLATFORMTHEME=hyprqt6engine

exec-once = systemctl --user start hyprpolkitagent
exec-once = udiskie
exec-once = waybar

EOF