#!/bin/bash

pacman -S --needed \
    hyprland \
    xdg-desktop-portal-hyprland \
    hyprpolkitagent \
    qt5-wayland \
    qt6-wayland \
    qt6-multimedia-ffmpeg \
    pipewire \
    wireplumber \
    nwg-look \
    hyprpaper \
    udiskie \
    waybar \
    ly \
    kitty \
    wofi \
    dolphin \
    dunst

CONFIG_FILE="$HOME/.config/hypr/hyprland.conf"

# remove autogenerated lines in hyprland.conf
sed -i '0,/autogenerated = 1/s//\#autogenerated = 1/' "$CONFIG_FILE"

# hyprqt6engine
# https://wiki.hypr.land/Hypr-Ecosystem/hyprqt6engine/
# set "QT_QPA_PLATFORMTHEME=hyprqt6engine". You can set this as env= in Hyprland,

# hyprpolkitagent
# https://wiki.hypr.land/Hypr-Ecosystem/hyprpolkitagent/
# Add "exec-once = systemctl --user start hyprpolkitagent" to your Hyprland config

# udiskie
# https://wiki.hypr.land/Useful-Utilities/Other/#automatically-mounting-using-udiskie
#  Add "exec-once = udiskie" to hyprland.conf 

# waybar
# https://wiki.hypr.land/Useful-Utilities/Status-Bars/#waybar
# Add "exec-once = waybar" to your Hyprland config

cat <<'EOF' >> "$CONFIG_FILE"

##############
### CUSTOM ###
##############

env=QT_QPA_PLATFORMTHEME=hyprqt6engine

exec-once = systemctl --user start hyprpolkitagent
exec-once = udiskie
exec-once = waybar

EOF